# Generated by Django 3.2.11 on 2022-01-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_accept_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='my_pic_id',
            new_name='requestee_pic_id',
        ),
    ]
